### ISSUE TITLE
support serialize protobuf dynamic class

### ISSUE THREAD

**Issue by wangyechao** [arextest/arex-agent-java#128]
when record dynamic class is protobuf occur error
we need support protobuf  serialize when dynamic  class  extends AbstractMessage

Stacktrace as follows:
```
[http-nio-8080-exec-5] WARN io.arex.foundation.serializer.GsonSerializer - serialize
java.lang.IllegalArgumentException: class RequestConfig declares multiple JSON fields named unknownFields
	at shaded.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172)
	at shaded.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at shaded.com.google.gson.Gson.getAdapter(Gson.java:489)
	at shaded.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
	at shaded.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
	at shaded.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
	at shaded.com.google.gson.Gson.toJson(Gson.java:735)
	at shaded.com.google.gson.Gson.toJson(Gson.java:714)
	at shaded.com.google.gson.Gson.toJson(Gson.java:669)
	at shaded.com.google.gson.Gson.toJson(Gson.java:649)
	at io.arex.foundation.serializer.GsonSerializer.serialize(GsonSerializer.java:184)
	at io.arex.inst.runtime.serializer.Serializer.serialize(Serializer.java:59)
	at io.arex.inst.dynamic.common.DynamicClassExtractor.record(DynamicClassExtractor.java:95)
	at io.arex.inst.dynamic.common.DynamicClassExtractor.setResponse(DynamicClassExtractor.java:65)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:331)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
```

**Comment by mr3** [comment]
Fixed in PR: #136, this issue will be closed. If you have any questions, please reopen it.
