### ISSUE TITLE
使用0.3.0版本的Agent无法启动项目

### ISSUE THREAD

**Issue by firmlybelieve** [arextest/arex-agent-java#175]
**Bug description**
使用0.3.0版本的Agent无法启动项目

**Steps to reproduce**
1.不加载agent项目启动成功，加载agent项目启动失败

**Expected behavior**
1.启动加载agent项目运行成功
**What went wrong?**
1.项目启动失败
**Environment**
java version: 1.8.0_281
arex-agent-java: 0.3.0

**Additional context**
If there is an exception, please attach the exception trace:

```
Just put your stack trace here!

异常信息如下：
[main] INFO io.arex.agent.instrumentation.InstrumentationInstaller - [arex] onTransformation: com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask loaded: false from classLoader org.springframework.boot.loader.LaunchedURLClassLoader@5c448433
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
        at io.arex.agent.bootstrap.internal.WeakCache.put(WeakCache.java:31)
        at java.util.concurrent.ForkJoinTask.<init>(Unknown Source)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.<init>(BoundedLocalCache.java:3273)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:239)
        at com.github.benmanes.caffeine.cache.SS.<init>(SS.java:32)
        at com.github.benmanes.caffeine.cache.SSMS.<init>(SSMS.java:66)
        at com.github.benmanes.caffeine.cache.SSMSW.<init>(SSMSW.java:42)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:98)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3357)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3353)
        at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:995)
        at com.mysoft.framework.cache.inner.caffeine.CaffeineCreator.createStandardCache(CaffeineCreator.java:35)
        at com.mysoft.framework.core.function.config.StandardConfigProvider.<init>(StandardConfigProvider.java:62)
        at com.mysoft.framework.modeling.configuration.runlistener.CoreSpringApplicationRunListener.contextPrepared(CoreSpringApplicationRunListener.java:79)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$contextPrepared$3(SpringApplicationRunListeners.java:67)
        at java.util.ArrayList.forEach(Unknown Source)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
        at org.springframework.boot.SpringApplicationRunListeners.contextPrepared(SpringApplicationRunListeners.java:67)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:403)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318)
        at com.mysoft.framework.container.CostApplication.main(CostApplication.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
        at io.arex.agent.bootstrap.internal.WeakCache.put(WeakCache.java:31)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.<init>(BoundedLocalCache.java:3275)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:239)
        at com.github.benmanes.caffeine.cache.SS.<init>(SS.java:32)
        at com.github.benmanes.caffeine.cache.SSMS.<init>(SSMS.java:66)
        at com.github.benmanes.caffeine.cache.SSMSW.<init>(SSMSW.java:42)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:98)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3357)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3353)
        at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:995)
        at com.mysoft.framework.cache.inner.caffeine.CaffeineCreator.createStandardCache(CaffeineCreator.java:35)
        at com.mysoft.framework.core.function.config.StandardConfigProvider.<init>(StandardConfigProvider.java:62)
        at com.mysoft.framework.modeling.configuration.runlistener.CoreSpringApplicationRunListener.contextPrepared(CoreSpringApplicationRunListener.java:79)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$contextPrepared$3(SpringApplicationRunListeners.java:67)
        at java.util.ArrayList.forEach(Unknown Source)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
        at org.springframework.boot.SpringApplicationRunListeners.contextPrepared(SpringApplicationRunListeners.java:67)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:403)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318)
        at com.mysoft.framework.container.CostApplication.main(CostApplication.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
[2023-05-22 11:44:14.226] [INFO ] [Jdk14Logger:log:87] [main] [-[No active profile set, falling back to default profiles: default]-]
[Thread-6] INFO io.arex.agent.instrumentation.InstrumentationInstaller - [arex] onTransformation: org.springframework.web.servlet.DispatcherServlet loaded: false from classLoader org.springframework.boot.loader.LaunchedURLClassLoader@5c448433
```

**Comment by mr3** [comment]
Please reopen this issue if you have further questions.
