### ISSUE TITLE
[Bug] mongo-driver-core 中find数据分页后getMore方法NPE

### ISSUE THREAD

**Issue by claywong** [arextest/arex-agent-java#487]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

mongoTemplate.find()数据条数超过100条，
只录制了100条数据
回放的时候会调用getMore方法，NPE

![image](https://github.com/arextest/arex-agent-java/assets/222770/72916a8f-b940-4c8b-af9f-1c7fb42ee199)

### Expected Behavior

预期录制所有游标数据

### Steps To Reproduce

mongo-driver-core
com.mongodb.operation.QueryBatchCursor#getMore

java.lang.NullPointerException: null
	at com.mongodb.operation.QueryBatchCursor.getMore(QueryBatchCursor.java:218)
	at com.mongodb.operation.QueryBatchCursor.hasNext(QueryBatchCursor.java:115)
	at com.mongodb.client.internal.MongoBatchCursorAdapter.hasNext(MongoBatchCursorAdapter.java:54)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2678)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2411)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2394)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:830)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:816)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by YongwuHe** [comment]
@claywong getMore已支持
