### ISSUE TITLE
[Bug] io.arex.agent.bootstrap.ctx.RunnableWrapper不支持有优先级的多线程

### ISSUE THREAD

**Issue by hanson772** [arextest/arex-agent-java#516]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

项目使用了线程池，提交有优先级的线程，导致程序运行失败。
io.arex.agent.bootstrap.ctx.RunnableWrapper cannot be cast to java.lang.Comparable, caused by: {}
java.lang.ClassCastException: io.arex.agent.bootstrap.ctx.RunnableWrapper cannot be cast to java.lang.Comparable
	at java.util.concurrent.PriorityBlockingQueue.siftUpComparable(PriorityBlockingQueue.java:358)
	at java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:490)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1371)
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:586)

### Expected Behavior

1

### Steps To Reproduce

1

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

**Comment by bjwhy** [comment]
i have met this issue too. RunnableWrapper needs to support  java.lang.Comparable

**Comment by YongwuHe** [comment]
@bjwhy @hanson772 han 已经fix
