### ISSUE TITLE
[Bug] Agent 0.4.6 启动异常，新增系统变量log4j2解析失败

### ISSUE THREAD

**Issue by pony-qd** [arextest/arex-agent-java#574]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

Springboot项目启动
不加载arex-agent启动正常
加载agent:0.4.4启动正常
加载agent:0.4.6启动异常
项目依赖信息如下：
![image](https://github.com/user-attachments/assets/1339c892-e6c4-4658-a230-167329946fcd)

![image](https://github.com/user-attachments/assets/3f8f419b-7592-4c66-a4df-fe4364de0d82)

### Expected Behavior

不产生异常

### Steps To Reproduce

异常信息如下：
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.apache.logging.log4j.util.PropertiesUtil
	at org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.java:71)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:60)
	at org.apache.commons.logging.LogFactory$Log4jLog.<clinit>(LogFactory.java:199)
	at org.apache.commons.logging.LogFactory$Log4jDelegate.createLog(LogFactory.java:166)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:109)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:99)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:198)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by pony-qd** [comment]
经过分析原因如下：
0.4.6版本，新增了系统属性，且设置为Map类型
![image](https://github.com/user-attachments/assets/041b0589-3cb6-4877-9e6e-0bd92c724c9c)

而log4j2-api
解析属性时统一为String,类型不匹配
![image](https://github.com/user-attachments/assets/7f4a17d9-046a-469b-93d0-2225a8b1fd9c)

**Comment by mr3** [comment]
@YongwuHe PTAL

**Comment by YongwuHe** [comment]
已修复，拉取最新版本即可，参考PR：fix: https://github.com/arextest/arex-agent-java/pull/580
